### PR TITLE
[WIP] Fix melodic build error in leg_detection_node

### PR DESCRIPTION
**Pull request by Sushant-Chavan**
Fixes build errors in Ubuntu Bionic. The last CI build for the melodic branch used the `bitbots/bitbots-common:kinetic` image as base and hence the build issues related to melodic are not visible.

@argenos is there a plan to create base images for the melodic branch? From [here](https://github.com/b-it-bots/mas_common_robotics/blob/93c35a421f8d162833b633e339b2b8a6f09b0e3d/Dockerfile#L1) I see that we are using kinetic base images even on the melodic branch.

## Changelog
* Use explicit template instantiation to fix the build error in mcr_leg_detection

## Checklist:

- [x] My code doesn't contain unnecessary comment blocks (e.g. unused code, templates of `package.xml` or `CMakeLists.txt`)
- [x] I have updated the `package.xml` and `CMakeLists.txt` with the correct dependencies.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sthoduka** [comment]
@Sushant-Chavan would you or someone else be able to create one?

**Comment by alex-mitrevski** [comment]
@Sushant-Chavan Due to time constraints, I think we won't migrate to melodic in @Home, so I think you guys should have a go at the migration without waiting on us. It's anyway the case that the new version of Ubuntu (and subsequently ROS) will come out in a few months, so maybe it makes sense to consider that version directly (but that assumes that the HSR will support the new version).

**Review by argenos — APPROVED** [review]

**Comment by argenos** [comment]
@Sushant-Chavan there are some melodic images in https://github.com/b-it-bots/docker/ but I won't have time to help with the migration. There is a melodic image for perception, see: https://hub.docker.com/repository/docker/bitbots/bitbots-perception. The `docker-compose.yaml` file needs to be updated to reflect that though.

**Comment by argenos** [comment]
The `Dockerfile` in the melodic branch also needs to be updated: https://github.com/b-it-bots/mas_perception/blob/melodic/.travis/Dockerfile#L13

**Pull request merged**
