### PR TITLE
Refactor/move find plane function

### PR DESCRIPTION
**Pull request by minhnh**
refactor cloud filtering and plane fitting for reuse in Python

### CODE REVIEW

**Review by sthoduka — APPROVED** [review]
looks fine. I haven't tested it though.

**Review by sthoduka — APPROVED** [review]
looks fine. I haven't tested it though

**Comment by minhnh** [comment]
@sthoduka I have tested `mcr_scene_segmentation` like how you told me. The object boxes and the inlaying plane points are shown in `rviz`.

**Comment by minhnh** [comment]
I have updated all the documentation for this PR. Can be merged now.
@sthoduka @alex-mitrevski @deebuls @argenos

**Review by alex-mitrevski — APPROVED** [review]

**Pull request merged**
